apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-parser-deployment
  labels:
    app: simple-parser-deployment-label
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-parser-pod-label
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: simple-parser-pod-label
    spec:
      containers:
        - name: simple-parser
          image: cr.selcloud.ru/dockerhub/simple-parser:{{ .Values.version }}
          command: ["npm", "run", "start:prod"]
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 150m
              memory: 50Mi
            limits:
              cpu: 200m
              memory: 100Mi
      imagePullSecrets:
        - name: regcred
